name: local_clipboard_sync
description: "A local network clipboard sync application in Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  network_info_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/icon/1.jfif"
  android: true
  ios: true
  min_sdk_android: 21 # لضمان توافق الأندرويد